### ISSUE TITLE
无法编译成功，难道是缺少lib目录依赖？

### ISSUE THREAD

**Issue by ainusers** [nyingping/flink_remotesubmit#1]
希望大佬不吝赐教

**Comment by nyingping** [comment]
报什么错？

**Comment by nyingping** [comment]
更新了maven配置，你再试下？

**Comment by nyingping** [comment]
如果编译指的是“flink模板jar包”不成功的话，在application里配置dependmentpath目录下加入flink的依赖包,由于使用的是maven,就没有上传，将maven依赖导出到dependmentpath下即可。

**Comment by ainusers** [comment]
还有一个问题呢，我看了您这个思路，效果是可以实现，但是用户每一次调试，都需要编译打包再上传flink-web是不是有些麻烦

另外，我之前实验的，可以通过createEnv去编写新的算子流程 (当然这里是针对于datastream来讲，不是flink sql)，这样就不需要编译打包再上传了

**Comment by nyingping** [comment]
提交方式可以选择不编译，选择上传编译好的jar文件。
嗯，createEnv方式也可以实现。
